run:
  timeout: 10m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters-settings:
  goimports:
    local-prefixes: github.com/bringg/spark-nanny

  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false

  exclude:
    # EXC0008 gosec: Duplicated errcheck checks
    # https://github.com/securego/gosec#available-rules
    - (G104|G307)

linters:
  presets:
    - unused
    - metalinter
    - format
    - bugs
  enable:
    - dogsled
    - goconst
    - gosimple
    - misspell
    - nakedret
    - unconvert
    - whitespace
  disable:
    - noctx
    - structcheck
    - deadcode
    - varcheck
    - scopelint
    - rowserrcheck
    - sqlclosecheck
