# Default values for spark-nanny.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # -- Image repository
  repository: bringg/spark-nanny
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Image pull secrets
imagePullSecrets: []

# -- String to partially override `spark-nanny.fullname` template (will maintain the release name)
nameOverride: ""

# -- String to override release name
fullnameOverride: ""

serviceAccount:
  # -- Additional annotations to add to the service account
  annotations: {}

# -- Comma separated list of spark apps to watch, e.g. spark-app1,spark-app2. Required
sparkApps: ""

# -- Listen port for health checks and metrics, change this if you're changing the `listen-address` argument
listenPort: 9164

# -- List of additional args to pass, e.g.
# - --interval=45
# - --debug
# - --dry-run
args: []

# -- Additional annotations to add to the pod
podAnnotations: {}

# -- Pod resource requests and limits
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Node labels for pod assignment
nodeSelector: {}

# -- List of node taints to tolerate
tolerations: []

# -- Affinity for pod assignment
affinity: {}
