apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spark-nanny.fullname" . }}
  labels:
    {{- include "spark-nanny.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-nanny.fullname" . }}
  labels:
    {{- include "spark-nanny.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spark-nanny.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "spark-nanny.fullname" . }}
  namespace: {{ .Release.Namespace }}

