apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-nanny.fullname" . }}
  labels:
    {{- include "spark-nanny.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

